twig:
    default_path: '%kernel.project_dir%/templates'
    
    globals:
        # Take the current year
        year: '@App\Service\ShowYear'

    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
